### PR TITLE
 POP-1193 initial version of popsync dashboard

### PR DESCRIPTION
**Pull request by mhyppone**
First version of Grafana dashboard for popsync

### CODE REVIEW

**Review by notjames — COMMENTED** [review]
currently getting an error when attempting to install the chart:
```
└>jimconn on jimconn-linux in helm/charts ・in  helm on  mhyppone/POP-1193/initial-popsync-dashboard [$!?] ・ﴱ (GEN3-PREPROD) b-stg1 (grafana) took 5s 
✦ at 11:39:41 ❯ helm upgrade --install gdb bluescape-monitoring-dashboards -n grafana --dry-run
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(GrafanaDashboard.spec): unknown field "name" in org.integreatly.v1alpha1.GrafanaDashboard.spec
```

I'm looking into it.

**Comment by notjames** [comment]
> currently getting an error when attempting to install the chart:
> 
> ```
> └>jimconn on jimconn-linux in helm/charts ・in  helm on  mhyppone/POP-1193/initial-popsync-dashboard [$!?] ・ﴱ (GEN3-PREPROD) b-stg1 (grafana) took 5s 
> ✦ at 11:39:41 ❯ helm upgrade --install gdb bluescape-monitoring-dashboards -n grafana --dry-run
> Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(GrafanaDashboard.spec): unknown field "name" in org.integreatly.v1alpha1.GrafanaDashboard.spec
> ```
> 
> I'm looking into it.


so something is using a `name` object in `.spec` which violates the spec. The following was used to flesh this out and apparently we have two problems.

1. The new popsync `dashboard.yaml` is an offender (probably the main offender).
2. The ambassador dashboard may asl be problematic so I'll check it also.

```
✦2 at 13:05:05 ❯ while read -r yf; do echo "$yf";  sed -r 's#.*\{\{.*\}\}#    nolabel: "true"#' "$yf" | yq -Mr '.spec.name?';done < <(find . -type f -name 'dashboard.yaml')
./21_custom-upstream-5xx-4xx-errors-rpm/dashboard.yaml
null
./91_linux_node_prometheus/dashboard.yaml
null
null
./10_qa-testgen/dashboard.yaml
null
./32_lambda_metrics_dashboard/dashboard.yaml
null
./20b_envoy-cluster-service-level/dashboard.yaml
null
./7_loki/dashboard.yaml
null
./15b_qa-front-end-summary/dashboard.yaml
null
./0_template/dashboard.yaml
null
./92a_elasticache_redis/dashboard.yaml
null
./1_argocd/dashboard.yaml
null
./80_filedescriptors_by_ns/dashboard.yaml
null
./11_qa-k6/dashboard.yaml
null
./14_falco/dashboard.yaml
null
./16c_ambassador-pod-selection/dashboard.yaml
null
./16a_ambassador-stats/dashboard.yaml
null
./94_synthetic_tests/dashboard.yaml
null
./84_backend_rendering_api_dashboard/dashboard.yaml
null
./16d_ambassador_edge_stack/dashboard.yaml
null
./101_performance-elementary/dashboard.yaml
null
./100_performance-image-upload/dashboard.yaml
null
./61_k8s-cluster-dashboard/dashboard.yaml
null
./5_k8s-worker-dashboard/dashboard.yaml
null
./51a_prometheus_alert_dashboard/dashboard.yaml
null
./22_nodejs_http_codes/dashboard.yaml
null
./98_self_serve_unified_dashboard/dashboard.yaml
null
./19_horizontal-pod-scaler/dashboard.yaml
null
./2_bull-exporter/dashboard.yaml
null
./12_unit-test-coverage/dashboard.yaml
null
./23_kube-pod-distribution/dashboard.yaml
null
./30_msk_exporter/dashboard.yaml
null
./7a_logging-operator/dashboard.yaml
null
./93_container_metrics/dashboard.yaml
null
./13_gatekeeper/dashboard.yaml
null
./82_certmanagement/dashboard.yaml
null
./95_nginx_ingress/dashboard.yaml
null
./6_dashboard-k8s-pod-states/dashboard.yaml
null
./81_node_filedescriptors/dashboard.yaml
null
./15_qa-front-end/dashboard.yaml
null
./97_entitler_errors/dashboard.yaml
yq: Error running jq: ParserError: while parsing a flow node
did not find expected node content
  in "<stdin>", line 7, column 8.
./9_postgres/dashboard.yaml
null
./83_document_upload_metrics/dashboard.yaml
null
./3_cortex/dashboard.yaml
null
./96_mongodb/dashboard.yaml
null
./8b_nginx_request_handling_performance/dashboard.yaml
null
./110_popsync_dashboard/dashboard.yaml
popsync--general-dashboard
./24_autoscaling/dashboard.yaml
null
./92_redis/dashboard.yaml
null
./31_mysql_metrics_dashboard/dashboard.yaml
null
./99_analytics_computeresources_pods_dashboard/dashboard.yaml
null
./8a_nginx/dashboard.yaml
null
./17_nodejs-metrics/dashboard.yaml
null
./20a_envoy-global/dashboard.yaml
null
./16b_ambassador-perf/dashboard.yaml
null
./60_unified_servicestatus_dashboard/dashboard.yaml
null
./4_express-app/dashboard.yaml
null
./16e_ambassador_upstream_5xx/dashboard.yaml
yq: Error running jq: ParserError: while parsing a flow node
did not find expected node content
  in "<stdin>", line 8, column 8.
./33_apollo_graphql_metrics/dashboard.yaml
null
./18_nodejs-apps/dashboard.yaml
null
./90_all-nodes/dashboard.yaml
null
```

**Comment by notjames** [comment]
OK, I fixed two dashboard.yaml files which only failed my test but were sound. However, there is one more dashboard which erroneously uses a `name` object in `.spec` and that is the `custom--envoy--5xx-4xx-upstream-errors-rateminute--dashboard` Lemme dig around for a min and see why that failed.

**Comment by notjames** [comment]
@mhyppone it looks like you may have manually done something with the popsync dashboard yaml? I am not 100% sure. At any rate, I've fixed it. You had an erroneous name property in `.spec`.

**Comment by notjames** [comment]
dry-run helm installation was successful. 
installing real deal in stg1 now.

**Review by notjames — APPROVED** [review]
@mhyppone please verify the dashboard in stg1. When you've verified it, please let me know and we can merge this.

**Comment by mhyppone** [comment]
@notjames Can't say why the yaml file was wrong, I didn't manually change anything. An accidental edit is possible I guess, but unlikely. Anyway, thanks for figuring it out. The charts look good in staging, looks like there's an issue with loki with log source in the stg env since I can see it in some other dashboards as well so not likely to do with this dashboard. Please go ahead with merge at your convenience

**Comment by MaharshPatelBluescape** [comment]
Followed the testing steps and have deployed the dashboard in UAT.

**Pull request merged**
